### PR TITLE
Fixed: ITV player now using https

### PR DESCRIPTION
**Pull request by petertribe**
ITV recently changed to use HTTPS which broke app detecting page content

### CODE REVIEW

**Comment by robincm** [comment]
Please can you tell us how we get this fix?
Thanks

**Comment by dinkypumpkin** [comment]
1. You need to make changes for Safari as well as Chrome
2. Be safe and support both http and https URLs. We don't want to have to revisit this if somebody messes up an ITV server config.
3. If you want to go the extra mile, do the same for BBC URLs. They are making noise about going https everywhere, though it will likely take a long time.

Squash your changes into a single commit.

**Comment by naq59** [comment]
Please could you tell us how we can make these changes to Safari now that ITV is using https or do we need to wait for a new release? Thanks for your great support.

**Comment by dinkypumpkin** [comment]
Rejected in favour of #630

**Pull request closed without merging**
